FROM php:8.2-apache

RUN a2enmod rewrite expires headers deflate

COPY apache-vhost-landing.conf /etc/apache2/sites-available/000-default.conf

COPY . /var/www/html/

RUN sed -i 's/DirectoryIndex index.html/DirectoryIndex 3-day-demo-class.html index.html/' /var/www/html/.htaccess \
 && mkdir -p /var/www/html/data \
 && chown -R www-data:www-data /var/www/html \
 && chmod -R 775 /var/www/html/data

EXPOSE 80
